---
count: 4
default:
  restart: 0
  wait: 1
editor:
  files:
    param:
      - lib/getopt-long-param.js
      - test/param-help..spec.js
      - test/param..spec.js
    opt:
      - lib/getopt-long.js
      - test/options-help..spec.js
      - test/options..spec.js
name: node-getopt-long
terminals:
  1:
    split: H
  1a:
    restart: 1
    wait: 0
    command: gulp
  2:
    edit: param
  3:
    edit: opt
